### PR TITLE
Bump to 0.6.3 with SortedMap

### PR DESCRIPTION
**Pull request by dilyand**

### CODE REVIEW

**Comment by chuwy** [comment]
Hi @dilyand! Can you remind me what we decided with it? Shall I close this PR?

**Comment by dilyand** [comment]
I'm not sure we made a decision. We fixed the immediate issue with a custom mapping function in the bad row aggregator. However, I think the long-term plan was still to eventually fix it here as well, to ensure we don't need the custom mapping every time we want to work with bad rows in Beam. If we have another solution, then the PR can be closed.

**Comment by chuwy** [comment]
I _think_ long-term solution was to not use Iglu Client in Bad Rows at all, but as we speak I now think that `SortedMap` in Iglu Client would not hurt anybody and probably will help us to avoid further problems with Beam.

So scheduling for 1.1.0.

**Comment by chuwy** [comment]
Cherry-picked into https://github.com/snowplow/iglu-scala-client/pull/148

**Pull request closed without merging**
